import type { Metadata } from "next";
import {AR_One_Sans} from "next/font/google"
import "./globals.css";

const arOneSans = AR_One_Sans({
  variable: "--font-ar-one",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arOneSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
